# Spring properties
spring:
  application:
     name: annotation-service


spring.datasource.driver-class-name: com.mysql.jdbc.Driver
spring.datasource.url: jdbc:mysql://localhost:3306/annotation?characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
spring.datasource.username: root
spring.datasource.password: root
spring.jpa.generate-ddl: true
spring.jpa.hibernate.ddl-auto: create
spring.jpa.show-sql: true
# Discovery Server Access
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://admin:123456@localhost:1111/eureka/
  instance:
    preferIpAddress: true
    instanceId: annotation-service-instance
# HTTP Server
server:
  port: 8081   # HTTP (Tomcat) port