# Spring properties
spring:
  application:
     name: authentication-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cat_authentication?characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    password:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create

# Discovery Server Access
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://admin:123456@localhost:1111/eureka/
  instance:
    preferIpAddress: true
    instanceId: annotation-service-instance

# HTTP Server
server:
  port: 8080   # HTTP (Tomcat) port