# Spring properties
spring:
  application:
     name: authentication-service
  data-source:
    url: jdbc:h2:mem:dev
    driver-class-name: org.h2.Driver


# Discovery Server Access
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://admin:123456@localhost:1111/eureka/
    instance:
      preferIpAddress: true
      instanceId: authentication-service-instance

# HTTP Server
server:
  port: 8080   # HTTP (Tomcat) port